// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxK_jHK21IdrK1dMcrffutoF2PAjqiu5Y',
    appId: '1:491344931824:web:e9daf44a2360c1a8ef0b35',
    messagingSenderId: '491344931824',
    projectId: 'pawtrack-7a4bc',
    authDomain: 'pawtrack-7a4bc.firebaseapp.com',
    storageBucket: 'pawtrack-7a4bc.firebasestorage.app',
    measurementId: 'G-BQPJ5CM7T1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmB9AIdI01Lw3J9V8M91URdHAJZUHXBE',
    appId: '1:491344931824:android:76afeddf7833da3aef0b35',
    messagingSenderId: '491344931824',
    projectId: 'pawtrack-7a4bc',
    storageBucket: 'pawtrack-7a4bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQxSpB1zasVqHLr6IUvqjz_FBv2VNx-e4',
    appId: '1:491344931824:ios:02ba49e64636d139ef0b35',
    messagingSenderId: '491344931824',
    projectId: 'pawtrack-7a4bc',
    storageBucket: 'pawtrack-7a4bc.firebasestorage.app',
    iosBundleId: 'com.example.pawtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQxSpB1zasVqHLr6IUvqjz_FBv2VNx-e4',
    appId: '1:491344931824:ios:02ba49e64636d139ef0b35',
    messagingSenderId: '491344931824',
    projectId: 'pawtrack-7a4bc',
    storageBucket: 'pawtrack-7a4bc.firebasestorage.app',
    iosBundleId: 'com.example.pawtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxK_jHK21IdrK1dMcrffutoF2PAjqiu5Y',
    appId: '1:491344931824:web:88551e6116927821ef0b35',
    messagingSenderId: '491344931824',
    projectId: 'pawtrack-7a4bc',
    authDomain: 'pawtrack-7a4bc.firebaseapp.com',
    storageBucket: 'pawtrack-7a4bc.firebasestorage.app',
    measurementId: 'G-DSS9NRRMQK',
  );
}
